### ISSUE TITLE
Improve the design and fix all the overflows.

### ISSUE THREAD

**Issue by ranjitkshah** [ranjitkshah/Covidapp#1]
1. Add a navbar and add your own design to it.
2. Add Dark Mode

**Comment by MeghalBisht** [comment]
Assign!

**Comment by abskrj** [comment]
Hey can you assign me any task?

**Comment by ranjitkshah** [comment]
@abhishekraj272  yes I am opening a new issue for dark mode toggle button you can help with that.
Thanks

**Comment by abskrj** [comment]
ok thanks
