### ISSUE TITLE
Dark Mode for the entire covid app

### ISSUE THREAD

**Issue by ranjitkshah** [ranjitkshah/Covidapp#3]
Add a toggle button using which we can switch between dark and light mode.
Also, keep all the existing styles js files in an organised manner by creating a styles folder.

**Comment by abskrj** [comment]
can you assign me here?

**Comment by ranjitkshah** [comment]
Sure! Go ahead :)

**Comment by sruthiragupathy** [comment]
Shall i work on this?

**Comment by abskrj** [comment]
@sruthiragupathy  I am already working
