### ISSUE TITLE
Make a Switch Theme button more interactive

### ISSUE THREAD

**Issue by Amulya-coder** [ranjitkshah/Covidapp#6]
Switch Theme button looks very simple use CSS and hover effect properties to make it more attractive.

**Comment by ranjitkshah** [comment]
do you want to work on it?

**Comment by Amulya-coder** [comment]
@ranjitkshah Sure. Kindly Assign it to me

**Comment by ranjitkshah** [comment]
> @ranjitkshah Sure. Kindly Assign it to me

Sure Go ahead!!
